[project]
name = "delta-lake-validation"
version = "0.1.0"
description = "Delta Lake Validation Suite"
authors = [
    {name = "granica.ai"},
]
dependencies = [
    "delta-spark==2.3.0",
    "google-cloud-storage==2.14.0",
    "pyspark==3.3.2"
]
requires-python = ">=3.8,<3.12"
readme = "README.md"
